services:
  mysql:
    image: mysql:8.0
    container_name: code-review-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: code_review_ide
      MYSQL_USER: app
      MYSQL_PASSWORD: app_pw
      MYSQL_ROOT_PASSWORD: root_pw
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]
    volumes:
      - code_review_mysql_data:/var/lib/mysql

volumes:
  code_review_mysql_data:
